### ISSUE TITLE
Stop illegally spying on hundreds of millions of people world wide

### ISSUE THREAD

**Issue by frap129** [NationalSecurityAgency/lemongrenade#1]

**Comment by ctubbsii** [comment]
Closed as spam.

**Comment by sfxworks** [comment]
@frap129 https://youtu.be/nMJT5hfTRig

**Comment by ctubbsii** [comment]
Removed inappropriate comment which harasses original poster. Even if the original post is spam, it's better not to encourage interpersonal attacks in retaliation.
